name: PocketRPG
main: PocketRPG\main
version: 0.1.0
api: [2.0.0]
author: Sandertv

commands:
  startquest:
    description: Start a quest
    usage: /startquest <number>
  listquest:
    description: Gives a list of quests
    usage: /listquest <number>
  seequest:
    description: See a currently opened quest
    usage: /seequest <number>
  endquest:
    description: Finish a quest
    usage: /endquest <number>
  rpgstart:
    description: Start your adventure
    usage: /startrpg <class>
