#Configuration for Quests plugin

#Amount of gold people will earn for completing a quest:
GOLD_AMOUNT_QUEST_1:
GOLD_AMOUNT_QUEST_2:
GOLD_AMOUNT_QUEST_3:
GOLD_AMOUNT_QUEST_4:
GOLD_AMOUNT_QUEST_5:
GOLD_AMOUNT_QUEST_6:
GOLD_AMOUNT_QUEST_7:
GOLD_AMOUNT_QUEST_8:
GOLD_AMOUNT_QUEST_9:
GOLD_AMOUNT_QUEST_10:
